import React from "react"
import Layout from "../../components/Layout"
import Head from "next/head"
import AlbumArtworkComponent from "@/components/Artwork"
import { Album } from "@mui/icons-material"


const ArtworkService = () => {
  return (
    <>
      <Head>
        <title>Album Artwork Services | Future Movement Beatz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logov2.png" />
      </Head>
      <Layout>
        <AlbumArtworkComponent />
      </Layout>
    </>
  )
}


export default ArtworkService