import React from "react"
import ProductTemplate from "../../templates/product-template"
import Layout from "../../components/Layout"
import Head from "next/head"


const ArtworkService = (serviceInfo) => {
    serviceInfo = {
        headerImageArtwork: true,
        title: 'Custom Album Artwork',
        introduction: 'Introduction for custom album artwork goes here',
        description: 'Description for custom album artwork goes here',
        faqs: [
            {
                question: 'FAQ Question 1',
                answer: 'FAQ Answer 1',
            },
            {
                question: 'FAQ Question 2',
                answer: 'FAQ Answer 2',
            },
            {
                question: 'FAQ Question 3',
                answer: 'FAQ Answer 3',
            },
        ]
    }
  return (
    <>
      <Head>
        <title>Album Artwork Services | Future Movement Beatz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logov2.png" />
      </Head>
      <Layout>
        <ProductTemplate
            {...serviceInfo}       
        />
      </Layout>
    </>
  )
}


export default ArtworkService