import React from "react"
import Layout from "../../components/Layout"
import Head from "next/head"
import MixingComponent from "@/components/MixingServiceContent"


const MixingService = (serviceInfo) => {
    serviceInfo = {
        headerImageMixing: true,
        title: 'Experience Sonic Brilliance',
        introduction: 'Music Mixing and Mastering by Abstraktius Artimus',
        description: 'Description for mixing and mastering goes here',
    }

  return (
    <>
      <Head>
        <title>Mixing Services | Future Movement Beatz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logov2.png" />
      </Head>      
      <Layout>
        <MixingComponent />
      </Layout>
    </>
  )
}


export default MixingService