import React from "react"
import TopNavigation from "@/components/TopNavigation"
import Footer from "@/components/Footer"
import Head from "next/head"
import MixingComponent from "@/components/MixingServiceContent"


const MixingService = () => {
  return (
    <>
      <Head>
        <title>Mixing Services | Future Movement Beatz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logov2.png" />
      </Head>      
      <TopNavigation />
      <MixingComponent />
      <Footer />
    </>
  )
}

export default MixingService