import React from "react"
import Layout from "../../components/Layout"
import Head from "next/head"
import ProductionComponent from "@/components/Production"


const ProductionService = () => {
  return (
    <>
      <Head>
        <title>Production Services | Future Movement Beatz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logov2.png" />
      </Head>
      <Layout>
        <ProductionComponent />
      </Layout>
    </>
  )
}

export default ProductionService