import * as React from "react"
import Head from "next/head"
import Button from "../components/Button"
import { 
    comingSoonDiv,
    comingSoonTitle,
    comingSoonInfo,
} from '../styles/ComingSoon.module.css'

const ComingSoon = () => {
    return (
        <>
            <Head>
            <title>Coming Soon | Future Movement Beatz</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logov2.png" />
            </Head>
                <div className={comingSoonDiv}>
                    <p className={comingSoonTitle}>Coming Soon</p>
                    <p className={comingSoonInfo}>Bear with us as our new site is being built.</p>
                    <Button
                        text="Home"
                        href="/"
                        arrow={true}
                    />
                </div>
        </>
    )
}

export default ComingSoon;