import * as React from "react"
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import Banner from "@/components/Banner"
import BannerText from "@/components/BannerText"
import FeaturedServices from "@/components/FeaturedServices"
import BannerVideo from "@/components/BannerVideo"
import FeaturedSingles from "@/components/FeaturedSingles"

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Future Movement Beatz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logov2.png" />
      </Head>
      <Layout>
        <Banner
          title="Future Movement Beatz"
          subTitle="Music production and custom album cover art."
          contact={false}        
        />
        <BannerText
        title="It is important that the musician just lets the music be written."
        content="- Bjork"
        link="/services"
        linkText="View Services"
      />
      <FeaturedServices
        title="What We Do"
        introduction="Let us help with your next album"
      />
      <BannerVideo 
        videoSrcURL1="https://www.youtube.com/embed/tLRp9vaY6VM"
        videoTitle1="Abstrakt Noize 3 Official Visualizer"
        videoSrcURL2="https://www.youtube.com/embed/0q5MEoA2Wyc"
        videoTitle2="Peace of Mind prod by Jiro"
      />
      <FeaturedSingles
        title="Latest Singles"
        introduction="Available to stream now"
      />
      </Layout>
    </>
  )
}
