import * as React from "react"
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import Banner from "@/components/Banner"
import BannerText from "@/components/BannerText"

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Future Movement Beatz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner
          title="Future Movement Beatz"
          subTitle="Music production and custom album cover art."
          contact={false}        
        />
        <BannerText
        title="It is important that the musician just lets the music be written."
        content="- Bjork"
        link="/services"
        linkText="View Services"
      />
      </Layout>
    </>
  )
}
